config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  # root 'pictures#index'
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    member do
      get :like
    end
  end
  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user, optional:true
  mount_uploader :image, ImageUploader
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :content, :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  before_validation { email.downcase! }
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
  
  private
  def logged_in_user
    unless logged_in?
      redirect_to new_session_path, notice: "ログインはお済みですか？"
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの写真をお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの写真をお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(post_params)
    else
      @picture = Picture.new
    end
  end
 
  def confirm
    
    @picture = Picture.new(picture_params)
    render :new if @picture.invalid?
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @picture.save
        PictureMailer.picture_mail(@picture).deliver 
        redirect_to pictures_path, notice: "投稿を作成しました！"
      else
        render :new
      end
    end
  end

  def show
    if logged_in?
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
    else
      redirect_to new_session_path, notice: "ログインが必要です"
    end
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "投稿を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"投稿を削除しました"
  end

  private
  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password]) 
      session[:user_id] = user.id
      redirect_to user_path(user.id) 
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    def destroy
      session.delete(:user_id)
      flash[:notice] = 'ログアウトしました'
      redirect_to new_session_path
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    render layout: false
  end

  def no_layout_action
    render layout: false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:show, :edit]
  before_action :logged_in_user, only:[:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:show, :edit, :update]

  def new
    @user =User.new
  end

  def create
    @user = User.new(user_params)
    # @user.image = "default.jpg"
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
     #binding.pry
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "プロフィールを編集しました！"
    else
      render :edit
    end
  end

  def like
    @user = User.find(params[:id])
    @favorites = @user.favorite_pictures.all
    #binding.pry
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to pictures_path, notice: "権限がありません"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

end

app/views/layouts/_footer.html.erb
<div class="footer"><br>
<i class="fab fa-facebook-square"></i><i class="fab fa-twitter-square"></i><br>
<p>Copyright ©2020 fastagram INC</p>
</div>

app/views/layouts/_header.html.erb
<div class="header">
<i class="fab fa-instagram"></i>
<h1><%= link_to "fastagram", pictures_path, class:"header_title" %></h1>
<div class="log_in">
<% if logged_in? %>
    <%= link_to "Myページ(ログイン中)", user_path(current_user.id),class:"edit_link", class: "btn btn-outline-primary" %>
    <%= link_to "ログアウト", session_path(current_user.id), method: :delete ,class:"edit_link", class: "btn btn-secondary" %>
<% else %>
    <%= link_to "Sign up", new_user_path, class:"edit_link",  class: "btn btn-outline-primary" %>
    <%= link_to "Login", new_session_path, class:"edit_link",  class: "btn btn-secondary" %>
<% end %>
</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">instagram</a>
    <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarForm" aria-controls="navbarForm" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarForm">
      <form class="d-flex ms-auto">
        <input class="form-control me-2" type="text" placeholder="検索..." aria-label="検索...">
        <button type="submit" class="btn btn-outline-success flex-shrink-0">検索</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/dd3b3c6e1f.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/navbar' %>
    <div class="alert alert-warning alert-dismissible fade show" >
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="閉じる"></button>
    </div>
    <div class="container">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pictures/confirm.html.erb
<div class="bg-light p-3 p-sm-5 my-4 rounded">
  <h3>以下の内容で、送信する。</h3>
</div>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  
  <p>投稿：<%= @picture.content %></p>
  <%= form.hidden_field :content %>
  
  <p>投稿画像：<%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></p>
  <%= form.hidden_field :image_cache %>
  <br>
  <%= form.submit  "送信する", class: "btn, btn-primary" %>
  
  <%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "やり直す", name: "back" %>
  <% end %>
  <% end %>

app/views/pictures/edit.html.erb
<div class="bg-light p-3 p-sm-5 my-4 rounded">
  <h1>編集する</h1>
</div>

<div class="w-50 mx-auto">
  <%= form_with(model: @picture, local: true) do |form| %>
    <div>
      <%= form.label :content, class: "col-form-label" %>
      <%= form.text_field :content, class: "form-control" %>
    </div><br>
    <div>
      <p>投稿中の画像：<%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></p><br>
      <%= form.hidden_field :image_cache %>
      <h4>別の画像に変更</h4><br>
      <%= form.label :image %>
      <%= form.file_field :image, class: "btn btn-lg, btn-secondary" %>
    </div><br>
    <%= form.submit "更新する", class: "btn btn-lg, btn-success" %>
  <% end %>
</div>

app/views/pictures/index.html.erb
<!-- About--><br><br>
   <section class="page-section bg-info shadow" id="intro">
       <div class="container">
           <div class="row justify-content-center">
               <div class="col-lg-8 text-center">
                   <h2 class="text-white mt-0">写真をシェアしよう！</h2>
                   <hr class="divider light my-4" />
                   <p class="text-white-50 mb-4">Start Bootstrap has everything you need to get your new website up and running in no time! Choose one of our open source, free to download, and easy to use themes! No strings attached!</p>
        <!-- 切り替えボタンの設定 -->
                   <button type="button" class="btn btn-outline-info btn-lg rounded-pill" data-bs-toggle="modal" data-bs-target="#exampleModal">
                     ログインして投稿
                   </button>
               </div>
           </div>
       </div>
   </section>
   
        <!-- モーダルの設定 -->
   <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel">
     <div class="modal-dialog modal-lg">
       <div class="modal-content">
         <div class="modal-header">
           <h5 class="modal-title" id="exampleModalLabel">ログイン画面</h5>
           <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
         </div>
         <div class="modal-body">
           <div class="mb-3">
             <label for="exampleInputEmail1" class="form-label">メールアドレス</label>
             <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
           </div>
           <div class="mb-3">
             <label for="exampleInputPassword1" class="form-label">パスワード</label>
             <input type="password" class="form-control" id="exampleInputPassword1">
             <span id="passwordHelpBlock" class="form-text">パスワードは、文字と数字を含めて8～20文字で、空白、特殊文字、絵文字を含むことはできません。</span>
           </div>
         </div>
         <div class="modal-footer">
           <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
           <button type="button" class="btn btn-primary">変更を保存</button>
         </div><!-- /.modal-footer -->
       </div><!-- /.modal-content -->
     </div><!-- /.modal-dialog -->
   </div><!-- /.modal -->


<br><br><br>
<div class="bg-light"><br>
<h4>投稿一覧</h4>
</div><br>

  <div class="row row-cols-2 row-cols-md-4 g-4">
<% @pictures.each do |picture| %>
    <div class="col">
      <div class="card h-100 shadow">
        <p class="card-img-top"><%= link_to image_tag(picture.image.url), picture_path(picture.id) %></p>
        <div class="card-body text-secondary">
          <p class="card-text"><small><%= picture.content %></small></p>
          <div class="card-footer">
            <div>
              <small><%= picture.created_at.strftime('%Y/%m/%d') %>_by</small>
              <span style="color:black;"><%= picture.user.name %></span>
            </div>
            <i class="fas fa-heart unlike-btn"><%= picture.favorites.count %></i><span>　</span>
            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>

            <% if logged_in? && current_user.id == picture.user_id %>
              <%= link_to '編集', edit_picture_path(picture.id), class: "btn btn-outline-success" %>
              <%= link_to '削除', picture_path(picture.id), class: "btn btn-outline-danger" , method: :delete, data: {confirm: "本当に削除していいですか？"} %>
              <% else %>
              <span>　</span>
              <span>　</span>
             <% end %>
            
          </div>
        </div>
      </div>
    </div>
<% end %>
  </div>
<br><br><hr>

<% if logged_in? %>
  <%= link_to '写真を投稿する', new_picture_path, class: "btn btn-lg, btn-primary" %>
<% else %>
  <%= link_to '写真を投稿する', new_session_path, class: "btn btn-outline-primary" %>
<% end %>
<br><br><hr>
<!-- About-->
   <section class="page-section bg-secondary" id="about">
       <div class="container">
           <div class="row justify-content-center">
               <div class="col-lg-8 text-center">
                   <h2 class="text-white mt-0">We've got what you need!</h2>
                   <hr class="divider light my-4" />
                   <p class="text-white-50 mb-4">Start Bootstrap has everything you need to get your new website up and running in no time! Choose one of our open source, free to download, and easy to use themes! No strings attached!</p>
                   <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Get Started!</a>
               </div>
           </div>
       </div>
   </section>

app/views/pictures/new.html.erb
<div class="bg-light p-3 p-sm-5 my-4 rounded">
  <h1>新規投稿</h1>
</div>

<% if @picture.errors.any? %>
    <div>
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>
<h3>投稿する</h3><br>
  <div class="w-50 mx-auto">
    <%= form_with(model: @picture, local: true, url: confirm_pictures_path ) do |form| %>
      <div class="mb-3">
        <%= form.label :content %>
        <%= form.text_field :content, class: "form-control" %>
      </div><br>
      <div>
        <%= form.label :image %>
        <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
        <%= form.file_field :image,  class: "btn btn-lg, btn-secondary" %>
        <%= form.hidden_field :image_cache %>
      </div>
      <br>
      <%= form.submit '投稿する',  class: "btn btn-lg, btn-primary" %>
    <% end %>
  </div>

app/views/pictures/show.html.erb
<div class="bg-light p-3 p-sm-5 my-4 rounded">
  <h1>投稿詳細画面</h1>
</div>
<p>内容: <%= @picture.content %></p>
<p>投稿画像: </p><%= image_tag @picture.image.url %>
<br>
<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to favorite_path(id: @favorite.id), method: :delete do %>
    <i class="fas fa-heart unlike-btn">いいね</i>
    <% end %>
  <% else %>
    <%= link_to favorites_path(picture_id: @picture.id), method: :post do%>
    <i class="far fa-heart like-btn">いいねする</i>
    <% end %>

  <% end %>
  <%= @picture.favorites.count %>
<% end %>
<br><hr>
<%= link_to "投稿一覧に戻る", pictures_path %>

app/views/tops/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <title>Document</title>
</head>
<body>
  <div class="up"></div>
  <div class="down"></div>
  <div class="line"></div>
  <div class="hero">
  <%= video_tag("/videos/video.mp4", autoplay: :true, loop: :true, muted: :true, class: 'video-content') %>
    <P class="top_page">Fastagram <br><%= link_to "Lorem Ipsum", pictures_path %></P>
  </div>
</video>
  <script>
    $(".line").animate({"width":"100%"},1500,function(){
      $(".line").css("right",0)
      $(".line").animate({"width":"0%"},1000,function(){
        $(".up").animate({"height":"0%"});
        $(".down").animate({"height":"0%"},500,function(){
          $("p").fadeIn("slow")
        });
      })
    })
  </script>
</body>
</html>

app/views/users/edit.html.erb
<div class="bg-light p-3 p-sm-5 my-4 rounded">
  <h1>ユーザー編集画面</h1>
  <p>現在の設定画像：<%= image_tag(@user.image.url(:thumb)) if @user.image && @user.image.url %></p>
</div>
  <h3>情報を編集する</h3><br>
    <%= form_with(model: @user, local: true) do |f| %>  
      <%= f.label :name %>
      <%= f.text_field :name %><br><br>
      <%= f.label :email %>
      <%= f.email_field :email %><br><br>
      <%= f.label :password %>
      <%= f.hidden_field :password, value: @user.password_digest %><br>
      <%= f.label :password_confirmation %>
      <%= f.hidden_field :password_confirmation, value: @user.password_digest %><br><br>
      <%= f.hidden_field :image_cache %>
      <%= f.label :image %>
      <%= f.file_field :image %> <br><br>
      <%= f.submit "編集する", class: "btn btn-lg, btn-primary" %>
    <% end %><br><hr>

  <%= link_to 'Myページに戻る', user_path(@user.id) %>

app/views/users/like.html.erb
<div class="bg-light p-3 p-sm-5 my-4 rounded">
  <h1>お気に入り一覧ページ</h1>
</div>

<h2>「いいね」した投稿：</h2>
  <% @favorites.each do |f| %>
    <ul>
      <li><%= f.user.name %>さんの投稿</li>
          <%= image_tag f.image.url %>
    </ul>
  <% end %><hr>
<%= link_to 'Myページに戻る', user_path(@user.id) %>

app/views/users/new.html.erb
<div class="bg-light p-3 p-sm-5 my-4 rounded">
  <h1>アカウント新規登録</h1>
</div>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :email %>
  <%= f.email_field :email %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br><br>
  <%= f.label :image %>
  <%= f.file_field :image %><br><br>

  <%= f.submit "アカウント登録", class: "btn btn-lg, btn-primary" %>
<% end %><br>
<%= link_to "みんなの投稿はこちら", pictures_path %>

app/views/users/show.html.erb
<div class="bg-light p-3 p-sm-5 my-4 rounded">
  <h1><%= @user.name %>のページ</h1>
  <p><%= image_tag @user.image.url(:thumb) %></p>
</div>


<p>ユーザー: <%= @user.name %></p>
<p>メールアドレス: <%= @user.email %></p>

<%= link_to '編集', edit_user_path(@user.id), class: "btn btn-lg, btn-primary" %><hr>
<p><%= link_to 'お気に入りした投稿一覧', like_user_path(@user.id) %></p>
<%= link_to "みんなの投稿を確認", pictures_path %>